### ISSUE TITLE
Windows sockopt for sending ECN

### ISSUE THREAD

**Issue by martinduke** [martinduke/udp-ecn#11]
This is not described in the text.

**Comment by guhetier** [comment]
Hi,

Windows doesn't have a sockopt for sending ECN on UDP at this time.
ECN can only be set on a per-packet basis using a cmsg (as already described in the document).

I created #17 to add clarify it + add a link to the IP_RECVECN online documentation.

**Comment by martinduke** [comment]
Fixed by #17
