### ISSUE TITLE
Include `sendmmsg` and `recvmmsg` on Linux?

### ISSUE THREAD

**Issue by mxinden** [martinduke/udp-ecn#4]
On Linux, one can send and receive ECN marked datagrams using `sendmmsg` and `recvmmsg` (note the two `m`s).

See for example:

https://github.com/quinn-rs/quinn/blob/bb02a12a8435a7732a1d762783eeacbb7e50418e/quinn-udp/src/unix.rs#L469-L470

Should this be included in the draft? If yes, I can prepare a PR.

**Comment by martinduke** [comment]
I think that adds clarity, so sure.
